[project]
name = "applied-math-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipywidgets>=8.1.5",
    "manim>=0.19.0",
    "matplotlib>=3.10.1",
]
